apiVersion: apps/v1
kind: Deployment
metadata:
  name: jzconsole-deployment
  namespace: jiaozifs
  labels:
    apptype: jzconsole
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: jzconsole
  template:
    metadata:
      labels:
        app: jzconsole
        apptype: jzconsole
    spec:
      containers:
        - name: jzconsole
          image: gitdatateam/jzconsole:{{ .Values.tag }}
          imagePullPolicy: Always
          env:
            - name: JIAOZIFS_API_URL
              value: {{ .Values.api_url }}
          ports:
            - containerPort: 80
