apiVersion: v1
kind: Service
metadata:
  name: jzconsole-service
  namespace: jiaozifs
  labels:
    apptype: jzconsole
spec:
  type: ClusterIP
  selector:
    app: jzconsole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
